// 생명의 계통수 데이터 v2 — 말단 노드 = '과(Family)', 바로 위 = '목(Order)'
// opts: s=학명, e=대표 생물, g=색 그룹, a=고정 위치(기준 좌표계), ca=자식 기본 방향, big=강조, ma=시기, ex=멸종, hl=강조 말단, sep=별도 계통(연결선 없음)
(function () {
  const T = (n, o = {}, ...kids) => ({ n, ...o, children: kids.length ? kids : undefined });
  const F = (n, s, e, o = {}) => ({ n, s, e, ...o });          // 과 (말단)
  const O = (n, s, ...fams) => fams.length === 1 ? { ...fams[0], ord: n } : T(n, { s }, ...fams); // 목 (과가 하나면 한 노드로 접음)

  window.TREE = T('LUCA', { s: '최종 공통 조상', ma: '약 40억 년 전', big: 3, g: 'root', a: [900, 2195] },

    // ───────── 세균 ─────────
    T('세균', { s: 'Bacteria', big: 2, g: 'bac', a: [560, 2110], ca: [300, 1960] },
      T('남세균문', { s: 'Cyanobacteriota' },
        O('노스톡목', 'Nostocales', F('노스톡과', 'Nostocaceae', '염주말')),
        O('시네코코쿠스목', 'Synechococcales', F('프로클로로코쿠스과', 'Prochlorococcaceae', '해양 광합성균'))),
      T('슈도모나스문', { s: 'Pseudomonadota' },
        O('장내세균목', 'Enterobacterales', F('장내세균과', 'Enterobacteriaceae', '대장균·살모넬라')),
        O('슈도모나스목', 'Pseudomonadales', F('슈도모나스과', 'Pseudomonadaceae', '녹농균')),
        O('리케차목', 'Rickettsiales', F('리케차과', 'Rickettsiaceae', '발진티푸스균'))),
      T('바실루스문', { s: 'Bacillota' },
        O('젖산균목', 'Lactobacillales', F('젖산균과', 'Lactobacillaceae', '유산균'), F('연쇄상구균과', 'Streptococcaceae', '폐렴구균')),
        O('바실루스목', 'Bacillales', F('바실루스과', 'Bacillaceae', '고초균·탄저균'), F('포도상구균과', 'Staphylococcaceae', '황색포도상구균'))),
      T('방선균문', { s: 'Actinomycetota' },
        O('스트렙토미세스목', 'Streptomycetales', F('스트렙토미세스과', 'Streptomycetaceae', '항생물질 생산균')),
        O('미코박테리움목', 'Mycobacteriales', F('미코박테리움과', 'Mycobacteriaceae', '결핵균'))),
      T('스피로헤타문', { s: 'Spirochaetota' },
        O('스피로헤타목', 'Spirochaetales', F('트레포네마과', 'Treponemataceae', '매독균')))
    ),

    // ───────── 고균 ─────────
    T('고균', { s: 'Archaea', big: 2, g: 'arc', a: [1180, 2150], ca: [1400, 2080] },
      T('유리고세균문', { s: 'Methanobacteriota' },
        O('메탄박테리움목', 'Methanobacteriales', F('메탄박테리움과', 'Methanobacteriaceae', '메탄생성균')),
        O('할로박테리움목', 'Halobacteriales', F('할로박테리움과', 'Halobacteriaceae', '호염균'))),
      T('써모프로테우스문', { s: 'Thermoproteota' },
        O('술폴로부스목', 'Sulfolobales', F('술폴로부스과', 'Sulfolobaceae', '호열·호산균'))),
      T('아스가르드 고균', { s: 'Asgardarchaeota', a: [1110, 2020] },

        // ───────── 진핵생물 ─────────
        T('진핵생물', { s: 'Eukarya', ma: '약 20억 년 전', big: 2, g: 'pro', a: [1000, 1880], ca: [700, 1920] },
          T('SAR', { s: '부등편모·피층·리자리아', a: [650, 1950], ca: [560, 2000] },
            O('다시마목', 'Laminariales', F('다시마과', 'Laminariaceae', '다시마'), F('미역과', 'Alariaceae', '미역')),
            O('혈포자충목', 'Haemosporida', F('말라리아원충과', 'Plasmodiidae', '말라리아 원충')),
            O('페니쿨리다목', 'Peniculida', F('짚신벌레과', 'Parameciidae', '짚신벌레'))),
          T('엑스카바타', { s: 'Excavata', a: [810, 2070] },
            O('유글레나목', 'Euglenales', F('유글레나과', 'Euglenaceae', '유글레나')),
            O('트리파노소마목', 'Trypanosomatida', F('트리파노소마과', 'Trypanosomatidae', '수면병 원충'))),
          T('아메보조아', { s: 'Amoebozoa', a: [960, 2080] },
            O('아메바목', 'Euamoebida', F('아메바과', 'Amoebidae', '아메바')),
            O('자루곰팡이목', 'Physarales', F('황색망사점균과', 'Physaraceae', '점균'))),

          // ───────── 식물 ─────────
          T('식물계', { s: 'Plantae', big: 2, g: 'pla', a: [560, 1720], ca: [420, 1720] },
            T('홍조식물문', { s: 'Rhodophyta' },
              O('김목', 'Bangiales', F('김과', 'Bangiaceae', '김')),
              O('우뭇가사리목', 'Gelidiales', F('우뭇가사리과', 'Gelidiaceae', '우뭇가사리'))),
            T('녹조식물문', { s: 'Chlorophyta' },
              O('갈파래목', 'Ulvales', F('갈파래과', 'Ulvaceae', '파래')),
              O('클라미도모나스목', 'Chlamydomonadales', F('클라미도모나스과', 'Chlamydomonadaceae', '클라미도모나스'))),
            T('육상식물', { s: 'Embryophyta', ma: '약 4.7억 년 전', a: [430, 1560] },
              T('선태식물', { s: 'Bryophyta s.l.' },
                O('솔이끼목', 'Polytrichales', F('솔이끼과', 'Polytrichaceae', '솔이끼')),
                O('우산이끼목', 'Marchantiales', F('우산이끼과', 'Marchantiaceae', '우산이끼'))),
              T('관다발식물', { s: 'Tracheophyta', a: [380, 1440] },
                T('석송식물문', { s: 'Lycopodiophyta' },
                  O('석송목', 'Lycopodiales', F('석송과', 'Lycopodiaceae', '석송'))),
                T('양치식물', { s: 'Polypodiopsida' },
                  O('고사리목', 'Polypodiales', F('잔고사리과', 'Dennstaedtiaceae', '고사리'), F('고란초과', 'Polypodiaceae', '고란초')),
                  O('속새목', 'Equisetales', F('속새과', 'Equisetaceae', '쇠뜨기·속새'))),
                T('종자식물', { s: 'Spermatophyta', a: [330, 1310] },
                  T('겉씨식물', { s: 'Gymnosperms', a: [160, 1430] },
                    O('구과목', 'Pinales', F('소나무과', 'Pinaceae', '소나무·전나무'), F('측백나무과', 'Cupressaceae', '세쿼이아·향나무'), F('주목과', 'Taxaceae', '주목')),
                    O('마황목', 'Gnetales', F('마황과', 'Ephedraceae', '마황')),
                    O('은행나무목', 'Ginkgoales', F('은행나무과', 'Ginkgoaceae', '은행나무')),
                    O('소철목', 'Cycadales', F('소철과', 'Cycadaceae', '소철'))),
                  T('속씨식물', { s: 'Angiosperms', ma: '약 1.4억 년 전', a: [360, 1170] },
                    O('수련목', 'Nymphaeales', F('수련과', 'Nymphaeaceae', '수련')),
                    O('목련목', 'Magnoliales', F('목련과', 'Magnoliaceae', '목련')),
                    O('녹나무목', 'Laurales', F('녹나무과', 'Lauraceae', '아보카도·계피')),
                    T('외떡잎식물', { s: 'Monocots', a: [150, 1170] },
                      O('벼목', 'Poales', F('벼과', 'Poaceae', '벼·밀·옥수수·대나무')),
                      O('천남성목', 'Alismatales', F('천남성과', 'Araceae', '토란·몬스테라')),
                      O('비짜루목', 'Asparagales', F('난초과', 'Orchidaceae', '난초'), F('수선화과', 'Amaryllidaceae', '양파·마늘')),
                      O('백합목', 'Liliales', F('백합과', 'Liliaceae', '백합·튤립')),
                      O('야자목', 'Arecales', F('야자과', 'Arecaceae', '야자나무')),
                      O('생강목', 'Zingiberales', F('파초과', 'Musaceae', '바나나'), F('생강과', 'Zingiberaceae', '생강·강황'))),
                    T('진정쌍떡잎식물', { s: 'Eudicots', a: [440, 1040] },
                      O('미나리아재비목', 'Ranunculales', F('미나리아재비과', 'Ranunculaceae', '미나리아재비'), F('양귀비과', 'Papaveraceae', '양귀비')),
                      O('석죽목', 'Caryophyllales', F('선인장과', 'Cactaceae', '선인장'), F('마디풀과', 'Polygonaceae', '메밀'), F('끈끈이귀개과', 'Droseraceae', '끈끈이주걱')),
                      T('장미군', { s: 'Rosids', a: [240, 930] },
                        O('장미목', 'Rosales', F('장미과', 'Rosaceae', '장미·사과·벚나무'), F('뽕나무과', 'Moraceae', '뽕나무·무화과')),
                        O('콩목', 'Fabales', F('콩과', 'Fabaceae', '콩·완두·아카시아')),
                        O('참나무목', 'Fagales', F('참나무과', 'Fagaceae', '참나무·밤나무')),
                        O('배추목', 'Brassicales', F('배추과', 'Brassicaceae', '배추·무·겨자')),
                        O('포도목', 'Vitales', F('포도과', 'Vitaceae', '포도')),
                        O('박목', 'Cucurbitales', F('박과', 'Cucurbitaceae', '오이·호박·수박')),
                        O('말피기목', 'Malpighiales', F('버드나무과', 'Salicaceae', '버드나무'), F('대극과', 'Euphorbiaceae', '고무나무')),
                        O('도금양목', 'Myrtales', F('도금양과', 'Myrtaceae', '유칼립투스')),
                        O('아욱목', 'Malvales', F('아욱과', 'Malvaceae', '목화·카카오')),
                        O('무환자나무목', 'Sapindales', F('운향과', 'Rutaceae', '귤·레몬'), F('단풍나무과', 'Sapindaceae', '단풍나무'))),
                      T('국화군', { s: 'Asterids', a: [630, 950] },
                        O('국화목', 'Asterales', F('국화과', 'Asteraceae', '해바라기·국화')),
                        O('가지목', 'Solanales', F('가지과', 'Solanaceae', '토마토·감자·고추')),
                        O('용담목', 'Gentianales', F('꼭두서니과', 'Rubiaceae', '커피나무')),
                        O('꿀풀목', 'Lamiales', F('꿀풀과', 'Lamiaceae', '라벤더·바질'), F('물푸레나무과', 'Oleaceae', '올리브')),
                        O('산형목', 'Apiales', F('미나리과', 'Apiaceae', '당근·미나리'), F('두릅나무과', 'Araliaceae', '인삼')),
                        O('진달래목', 'Ericales', F('진달래과', 'Ericaceae', '진달래·블루베리'), F('차나무과', 'Theaceae', '차나무')))
                    )
                  )
                )
              )
            )
          ),

          T('후편모생물', { s: 'Opisthokonta', a: [1080, 1740] },
            // ───────── 균류 ─────────
            T('균계', { s: 'Fungi', big: 2, g: 'fun', a: [870, 1620], ca: [800, 1440] },
              T('항아리곰팡이문', { s: 'Chytridiomycota' },
                O('항아리곰팡이목', 'Chytridiales', F('항아리곰팡이과', 'Chytridiaceae', '항아리곰팡이'))),
              O('털곰팡이목', 'Mucorales', F('털곰팡이과', 'Mucoraceae', '털곰팡이·거미줄곰팡이')),
              T('자낭균문', { s: 'Ascomycota' },
                O('효모목', 'Saccharomycetales', F('효모과', 'Saccharomycetaceae', '빵·맥주 효모')),
                O('유로티움목', 'Eurotiales', F('누룩곰팡이과', 'Aspergillaceae', '누룩·푸른곰팡이')),
                O('주발버섯목', 'Pezizales', F('곰보버섯과', 'Morchellaceae', '곰보버섯'), F('덩이버섯과', 'Tuberaceae', '트러플')),
                O('육좌균목', 'Hypocreales', F('동충하초과', 'Cordycipitaceae', '동충하초'))),
              T('담자균문', { s: 'Basidiomycota' },
                O('주름버섯목', 'Agaricales', F('광대버섯과', 'Amanitaceae', '광대버섯'), F('송이버섯과', 'Tricholomataceae', '송이'), F('솔밭버섯과', 'Omphalotaceae', '표고버섯')),
                O('그물버섯목', 'Boletales', F('그물버섯과', 'Boletaceae', '포르치니')),
                O('목이목', 'Auriculariales', F('목이과', 'Auriculariaceae', '목이버섯')))
            ),

            // ───────── 동물 ─────────
            T('동물계', { s: 'Animalia', ma: '약 6억 년 전', big: 2, g: 'inv', a: [1270, 1640], ca: [1520, 1740] },
              T('해면동물문', { s: 'Porifera' },
                O('육방해면목', 'Lyssacinosida', F('해로동굴해면과', 'Euplectellidae', '비너스의 꽃바구니'))),
              T('자포동물문', { s: 'Cnidaria' },
                O('기구해파리목', 'Semaeostomeae', F('느릅나무해파리과', 'Ulmaridae', '보름달물해파리')),
                O('돌산호목', 'Scleractinia', F('사슴뿔산호과', 'Acroporidae', '사슴뿔산호')),
                O('해변말미잘목', 'Actiniaria', F('해변말미잘과', 'Actiniidae', '말미잘'))),
              T('좌우대칭동물', { s: 'Bilateria', a: [1290, 1470] },
                T('선구동물', { s: 'Protostomia', a: [1450, 1330] },
                  T('촉수담륜동물', { s: 'Lophotrochozoa', a: [1600, 1520], ca: [1660, 1640] },
                    O('세갈래창자목', 'Tricladida', F('플라나리아과', 'Dugesiidae', '플라나리아')),
                    O('후생빈모목', 'Crassiclitellata', F('낚시지렁이과', 'Lumbricidae', '지렁이')),
                    T('연체동물문', { s: 'Mollusca' },
                      O('문어목', 'Octopoda', F('문어과', 'Octopodidae', '문어·낙지')),
                      O('살오징어목', 'Oegopsida', F('살오징어과', 'Ommastrephidae', '오징어')),
                      O('병안목', 'Stylommatophora', F('달팽이과', 'Helicidae', '달팽이')),
                      O('굴목', 'Ostreida', F('굴과', 'Ostreidae', '굴')),
                      O('홍합목', 'Mytilida', F('홍합과', 'Mytilidae', '홍합')))),
                  T('탈피동물', { s: 'Ecdysozoa', a: [1480, 1170] },
                    O('간선충목', 'Rhabditida', F('간선충과', 'Rhabditidae', '예쁜꼬마선충')),
                    T('절지동물문', { s: 'Arthropoda', a: [1520, 1030], ca: [1680, 1120] },
                      O('파콥스목', 'Phacopida', F('파콥스과', 'Phacopidae', '삼엽충', { ex: 1 })),
                      O('왕지네목', 'Scolopendromorpha', F('왕지네과', 'Scolopendridae', '왕지네')),
                      T('협각아문', { s: 'Chelicerata' },
                        O('거미목', 'Araneae', F('왕거미과', 'Araneidae', '왕거미'), F('깡충거미과', 'Salticidae', '깡충거미')),
                        O('전갈목', 'Scorpiones', F('뷰티드과', 'Buthidae', '전갈')),
                        O('검미목', 'Xiphosura', F('투구게과', 'Limulidae', '투구게')),
                        O('참진드기목', 'Ixodida', F('참진드기과', 'Ixodidae', '진드기'))),
                      T('갑각아문', { s: 'Crustacea' },
                        O('십각목', 'Decapoda', F('꽃게과', 'Portunidae', '꽃게'), F('보리새우과', 'Penaeidae', '새우'), F('가재과', 'Astacidae', '가재')),
                        O('등각목', 'Isopoda', F('쥐며느리과', 'Porcellionidae', '쥐며느리')),
                        O('난바다곤쟁이목', 'Euphausiacea', F('난바다곤쟁이과', 'Euphausiidae', '크릴'))),
                      T('곤충강', { s: 'Insecta', big: 1, a: [1560, 880], ca: [1640, 840] },
                        O('하루살이목', 'Ephemeroptera', F('하루살이과', 'Ephemeridae', '하루살이')),
                        O('잠자리목', 'Odonata', F('잠자리과', 'Libellulidae', '고추잠자리')),
                        O('메뚜기목', 'Orthoptera', F('메뚜기과', 'Acrididae', '메뚜기'), F('귀뚜라미과', 'Gryllidae', '귀뚜라미')),
                        O('바퀴목', 'Blattodea', F('왕바퀴과', 'Blattidae', '이질바퀴'), F('흰개미과', 'Termitidae', '흰개미')),
                        O('사마귀목', 'Mantodea', F('사마귀과', 'Mantidae', '사마귀')),
                        O('노린재목', 'Hemiptera', F('매미과', 'Cicadidae', '매미'), F('진딧물과', 'Aphididae', '진딧물')),
                        O('딱정벌레목', 'Coleoptera', F('무당벌레과', 'Coccinellidae', '무당벌레'), F('사슴벌레과', 'Lucanidae', '사슴벌레')),
                        O('나비목', 'Lepidoptera', F('호랑나비과', 'Papilionidae', '호랑나비')),
                        O('벌목', 'Hymenoptera', F('꿀벌과', 'Apidae', '꿀벌'), F('개미과', 'Formicidae', '개미')),
                        O('파리목', 'Diptera', F('모기과', 'Culicidae', '모기'), F('집파리과', 'Muscidae', '집파리')),
                        O('벼룩목', 'Siphonaptera', F('벼룩과', 'Pulicidae', '벼룩')),
                        O('풀잠자리목', 'Neuroptera', F('풀잠자리과', 'Chrysopidae', '풀잠자리')),
                        O('대벌레목', 'Phasmida', F('대벌레과', 'Phasmatidae', '대벌레')))
                    )
                  )
                ),
                T('후구동물', { s: 'Deuterostomia', a: [1130, 1360] },
                  T('극피동물문', { s: 'Echinodermata', a: [1330, 1420] },
                    O('겸자불가사리목', 'Forcipulatida', F('불가사리과', 'Asteriidae', '불가사리')),
                    O('만두성게목', 'Camarodonta', F('둥근성게과', 'Strongylocentrotidae', '성게')),
                    O('순수목', 'Synallactida', F('돌기해삼과', 'Stichopodidae', '해삼'))),
                  T('척삭동물문', { s: 'Chordata', g: 'fish', a: [1060, 1250] },
                    O('측구목', 'Stolidobranchia', F('멍게과', 'Pyuridae', '멍게')),
                    O('창고기목', 'Amphioxiformes', F('창고기과', 'Branchiostomatidae', '창고기')),
                    T('척추동물', { s: 'Vertebrata', ma: '약 5.2억 년 전', big: 1, a: [990, 1140], ca: [1160, 1120] },
                      O('칠성장어목', 'Petromyzontiformes', F('칠성장어과', 'Petromyzontidae', '칠성장어')),
                      T('연골어강', { s: 'Chondrichthyes' },
                        O('흉상어목', 'Carcharhiniformes', F('흉상어과', 'Carcharhinidae', '뱀상어')),
                        O('악상어목', 'Lamniformes', F('악상어과', 'Lamnidae', '백상아리')),
                        O('수염상어목', 'Orectolobiformes', F('고래상어과', 'Rhincodontidae', '고래상어')),
                        O('홍어목', 'Rajiformes', F('홍어과', 'Rajidae', '홍어'))),
                      T('경골어류', { s: 'Osteichthyes', a: [960, 1020] },
                        T('조기어강', { s: 'Actinopterygii', a: [1180, 1000], ca: [1250, 1120] },
                          O('철갑상어목', 'Acipenseriformes', F('철갑상어과', 'Acipenseridae', '철갑상어')),
                          O('연어목', 'Salmoniformes', F('연어과', 'Salmonidae', '연어·송어')),
                          O('잉어목', 'Cypriniformes', F('잉어과', 'Cyprinidae', '잉어·붕어')),
                          O('고등어목', 'Scombriformes', F('고등어과', 'Scombridae', '참치·고등어')),
                          O('뱀장어목', 'Anguilliformes', F('뱀장어과', 'Anguillidae', '뱀장어'), F('곰치과', 'Muraenidae', '곰치')),
                          O('청어목', 'Clupeiformes', F('청어과', 'Clupeidae', '청어·정어리'), F('멸치과', 'Engraulidae', '멸치')),
                          O('메기목', 'Siluriformes', F('메기과', 'Siluridae', '메기')),
                          O('아귀목', 'Lophiiformes', F('아귀과', 'Lophiidae', '아귀')),
                          O('가자미목', 'Pleuronectiformes', F('넙치과', 'Paralichthyidae', '광어'), F('가자미과', 'Pleuronectidae', '가자미')),
                          O('복어목', 'Tetraodontiformes', F('참복과', 'Tetraodontidae', '복어'), F('개복치과', 'Molidae', '개복치')),
                          O('농어목', 'Perciformes', F('쏨뱅이과', 'Scorpaenidae', '쏨뱅이·쏠배감펭')),
                          O('망둑어목', 'Gobiiformes', F('망둑어과', 'Gobiidae', '망둑어')),
                          O('실고기목', 'Syngnathiformes', F('실고기과', 'Syngnathidae', '해마'))),
                        T('육기어류', { s: 'Sarcopterygii', a: [920, 920] },
                          O('실러캔스목', 'Coelacanthiformes', F('라티메리아과', 'Latimeriidae', '실러캔스')),
                          O('케라토두스목', 'Ceratodontiformes', F('레피도시렌과', 'Lepidosirenidae', '폐어')),
                          T('사지동물', { s: 'Tetrapoda', ma: '약 3.7억 년 전', g: 'amp', a: [920, 820], ca: [1080, 860] },
                            T('양서강', { s: 'Amphibia' },
                              O('무미목', 'Anura', F('청개구리과', 'Hylidae', '청개구리'), F('개구리과', 'Ranidae', '참개구리')),
                              O('유미목', 'Caudata', F('도롱뇽과', 'Hynobiidae', '도롱뇽'), F('점박이도롱뇽과', 'Ambystomatidae', '아홀로틀')),
                              O('무족목', 'Gymnophiona', F('무족영원과', 'Caeciliidae', '무족영원'))),
                            T('양막류', { s: 'Amniota', a: [930, 720] },
                              T('석형류', { s: 'Sauropsida', g: 'rep', big: 1, a: [1120, 660], ca: [1320, 730] },
                                O('거북목', 'Testudines', F('바다거북과', 'Cheloniidae', '바다거북'), F('남생이과', 'Geoemydidae', '남생이')),
                                O('옛도마뱀목', 'Rhynchocephalia', F('옛도마뱀과', 'Sphenodontidae', '투아타라')),
                                O('유린목', 'Squamata', F('도마뱀과', 'Scincidae', '도마뱀'), F('이구아나과', 'Iguanidae', '이구아나'), F('카멜레온과', 'Chamaeleonidae', '카멜레온'), F('왕도마뱀과', 'Varanidae', '코모도왕도마뱀'), F('비단뱀과', 'Pythonidae', '비단뱀'), F('코브라과', 'Elapidae', '코브라'), F('살모사과', 'Viperidae', '살모사')),
                                T('지배파충류', { s: 'Archosauria', a: [1230, 560] },
                                  O('악어목', 'Crocodylia', F('악어과', 'Crocodylidae', '나일악어'), F('앨리게이터과', 'Alligatoridae', '앨리게이터')),
                                  T('공룡', { s: 'Dinosauria', a: [1280, 440], ca: [1170, 400] },
                                    O('조반목', 'Ornithischia', F('케라톱스과', 'Ceratopsidae', '트리케라톱스', { ex: 1 })),
                                    T('용반목', { s: 'Saurischia', a: [1330, 340], ca: [1200, 300] },
                                      F('브라키오사우루스과', 'Brachiosauridae', '브라키오사우루스', { ex: 1 }),
                                      F('티라노사우루스과', 'Tyrannosauridae', '티라노사우루스', { ex: 1 }),
                                      T('조강', { s: 'Aves', big: 1, g: 'bird', a: [1490, 400], ca: [1580, 330] },
                                        O('타조목', 'Struthioniformes', F('타조과', 'Struthionidae', '타조')),
                                        O('펭귄목', 'Sphenisciformes', F('펭귄과', 'Spheniscidae', '황제펭귄')),
                                        O('닭목', 'Galliformes', F('꿩과', 'Phasianidae', '닭·꿩')),
                                        O('기러기목', 'Anseriformes', F('오리과', 'Anatidae', '오리·기러기')),
                                        O('두루미목', 'Gruiformes', F('두루미과', 'Gruidae', '두루미')),
                                        O('사다새목', 'Pelecaniformes', F('백로과', 'Ardeidae', '백로·왜가리')),
                                        O('비둘기목', 'Columbiformes', F('비둘기과', 'Columbidae', '비둘기·도도†')),
                                        O('칼새목', 'Apodiformes', F('벌새과', 'Trochilidae', '벌새')),
                                        O('수리목', 'Accipitriformes', F('수리과', 'Accipitridae', '독수리·참수리')),
                                        O('올빼미목', 'Strigiformes', F('올빼미과', 'Strigidae', '올빼미·부엉이')),
                                        O('파랑새목', 'Coraciiformes', F('물총새과', 'Alcedinidae', '물총새')),
                                        O('딱다구리목', 'Piciformes', F('딱다구리과', 'Picidae', '딱따구리')),
                                        O('매목', 'Falconiformes', F('매과', 'Falconidae', '매·황조롱이')),
                                        O('앵무목', 'Psittaciformes', F('앵무과', 'Psittacidae', '앵무새')),
                                        O('참새목', 'Passeriformes', F('참새과', 'Passeridae', '참새'), F('까마귀과', 'Corvidae', '까마귀·까치')))
                                    )
                                  )
                                )
                              ),
                              T('단궁류', { s: 'Synapsida', g: 'mam', a: [800, 690] },
                                O('반룡목', 'Pelycosauria', F('스페나코돈과', 'Sphenacodontidae', '디메트로돈', { ex: 1 })),
                                T('포유강', { s: 'Mammalia', ma: '약 2억 년 전', big: 1, a: [690, 610], ca: [520, 470] },
                                  O('단공목', 'Monotremata', F('오리너구리과', 'Ornithorhynchidae', '오리너구리')),
                                  O('주머니쥐목', 'Didelphimorphia', F('주머니쥐과', 'Didelphidae', '주머니쥐')),
                                  O('캥거루목', 'Diprotodontia', F('캥거루과', 'Macropodidae', '캥거루'), F('코알라과', 'Phascolarctidae', '코알라')),
                                  T('태반류', { s: 'Placentalia', a: [580, 520] },
                                    O('장비목', 'Proboscidea', F('코끼리과', 'Elephantidae', '코끼리')),
                                    O('바다소목', 'Sirenia', F('매너티과', 'Trichechidae', '매너티')),
                                    O('유모목', 'Pilosa', F('세발가락나무늘보과', 'Bradypodidae', '나무늘보'), F('개미핥기과', 'Myrmecophagidae', '큰개미핥기')),
                                    O('피갑목', 'Cingulata', F('아르마딜로과', 'Dasypodidae', '아르마딜로')),
                                    T('영장상목', { s: 'Euarchontoglires', a: [720, 410], ca: [780, 320] },
                                      O('설치목', 'Rodentia', F('쥐과', 'Muridae', '생쥐·집쥐'), F('다람쥐과', 'Sciuridae', '다람쥐'), F('비버과', 'Castoridae', '비버'), F('호저과', 'Hystricidae', '호저')),
                                      O('나무두더지목', 'Scandentia', F('나무두더지과', 'Tupaiidae', '나무두더지')),
                                      O('토끼목', 'Lagomorpha', F('토끼과', 'Leporidae', '토끼')),
                                      T('영장목', { s: 'Primates', a: [860, 330], ca: [960, 260] },
                                        F('여우원숭이과', 'Lemuridae', '여우원숭이'),
                                        F('안경원숭이과', 'Tarsiidae', '안경원숭이'),
                                        F('꼬리감는원숭이과', 'Cebidae', '꼬리감는원숭이'),
                                        F('긴꼬리원숭이과', 'Cercopithecidae', '개코원숭이'),
                                        F('긴팔원숭이과', 'Hylobatidae', '긴팔원숭이'),
                                        F('사람과', 'Hominidae', '사람·침팬지·고릴라', { hl: 1 }))
                                    ),
                                    T('로라시아상목', { s: 'Laurasiatheria', a: [420, 520], ca: [300, 430] },
                                      O('진무맹장목', 'Eulipotyphla', F('두더지과', 'Talpidae', '두더지'), F('고슴도치과', 'Erinaceidae', '고슴도치')),
                                      O('천산갑목', 'Pholidota', F('천산갑과', 'Manidae', '천산갑')),
                                      O('박쥐목', 'Chiroptera', F('관박쥐과', 'Rhinolophidae', '관박쥐')),
                                      T('식육목', { s: 'Carnivora', a: [230, 360] },
                                        F('고양이과', 'Felidae', '고양이·사자·호랑이'), F('개과', 'Canidae', '개·늑대·여우'),
                                        F('곰과', 'Ursidae', '불곰·판다'), F('하이에나과', 'Hyaenidae', '하이에나'), F('족제비과', 'Mustelidae', '족제비·수달'), F('물범과', 'Phocidae', '물범')),
                                      O('기제목', 'Perissodactyla', F('말과', 'Equidae', '말·얼룩말'), F('코뿔소과', 'Rhinocerotidae', '코뿔소')),
                                      T('경우제목', { s: 'Cetartiodactyla', a: [330, 650], ca: [180, 700] },
                                        F('낙타과', 'Camelidae', '낙타·알파카'), F('사슴과', 'Cervidae', '사슴'), F('기린과', 'Giraffidae', '기린'), F('소과', 'Bovidae', '소·양·염소'), F('멧돼지과', 'Suidae', '돼지'), F('하마과', 'Hippopotamidae', '하마'),
                                        F('수염고래과', 'Balaenopteridae', '흰긴수염고래'), F('참돌고래과', 'Delphinidae', '돌고래·범고래'))
                                    )
                                  )
                                )
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
  );

  // ───────── 바이러스 (비세포성 · 별도 계통) ─────────
  window.VIRUS = T('바이러스', { s: 'Viruses · 비세포성', big: 2, g: 'vir', a: [1620, 2200], ca: [1600, 2000] },
    T('리보비리아', { s: 'Riboviria · RNA', a: [1540, 2000], ca: [1560, 1880] },
      O('니도바이러스목', 'Nidovirales', F('코로나바이러스과', 'Coronaviridae', '사스·코로나19')),
      O('모노네가바이러스목', 'Mononegavirales', F('파라믹소바이러스과', 'Paramyxoviridae', '홍역'), F('필로바이러스과', 'Filoviridae', '에볼라')),
      O('아티쿨라바이러스목', 'Articulavirales', F('오르토믹소바이러스과', 'Orthomyxoviridae', '인플루엔자')),
      O('피코르나바이러스목', 'Picornavirales', F('피코르나바이러스과', 'Picornaviridae', '소아마비·감기')),
      O('오르테르바이러스목', 'Ortervirales', F('레트로바이러스과', 'Retroviridae', 'HIV'))),
    T('두플로드나비리아', { s: 'Duplodnaviria · dsDNA', a: [1700, 2080] },
      O('헤르페스바이러스목', 'Herpesvirales', F('헤르페스바이러스과', 'Orthoherpesviridae', '수두·대상포진'))),
    T('바리드나비리아', { s: 'Varidnaviria · dsDNA', a: [1700, 2290] },
      O('키토바이러스목', 'Chitovirales', F('폭스바이러스과', 'Poxviridae', '천연두·엠폭스')),
      O('로와바이러스목', 'Rowavirales', F('아데노바이러스과', 'Adenoviridae', '아데노바이러스')),
      O('이미터바이러스목', 'Imitervirales', F('미미바이러스과', 'Mimiviridae', '거대 바이러스'))),
    T('모노드나비리아', { s: 'Monodnaviria · DNA', a: [1480, 2280] },
      O('추르하우젠바이러스목', 'Zurhausenvirales', F('파필로마바이러스과', 'Papillomaviridae', 'HPV')))
  );

  // 색 그룹 (동일 명도·채도, 색상만 변화)
  // 계통별 배치 영역 [x0, y0, x1, y1] (기준 좌표계) — 자유 노드가 다른 계통으로 넘어가지 않게
  window.BOX = {
    mam:  [60, 20, 930, 760],   rep: [940, 20, 1740, 770], bird: [1180, 20, 1740, 740],
    amp:  [780, 740, 1180, 960], fish: [860, 880, 1290, 1330],
    inv:  [1250, 790, 1740, 1790], fun: [700, 1300, 1180, 1800],
    pla:  [60, 780, 720, 1820],  pro: [560, 1820, 1080, 2170],
    bac:  [60, 1830, 600, 2310], arc: [1060, 1960, 1400, 2310], vir: [1420, 1820, 1740, 2310],
  };

  window.GROUPS = {
    root: { c: 'oklch(0.74 0.02 210)', name: '공통 조상' },
    bac:  { c: 'oklch(0.74 0.07 245)', name: '세균' },
    arc:  { c: 'oklch(0.74 0.07 290)', name: '고균' },
    pro:  { c: 'oklch(0.76 0.09 195)', name: '원생생물' },
    pla:  { c: 'oklch(0.80 0.15 145)', name: '식물' },
    fun:  { c: 'oklch(0.80 0.07 75)',  name: '균류' },
    inv:  { c: 'oklch(0.76 0.13 320)', name: '무척추동물' },
    fish: { c: 'oklch(0.78 0.11 235)', name: '어류·척삭동물' },
    amp:  { c: 'oklch(0.80 0.12 170)', name: '양서류' },
    rep:  { c: 'oklch(0.76 0.14 35)',  name: '파충류' },
    bird: { c: 'oklch(0.78 0.13 15)',  name: '조류' },
    mam:  { c: 'oklch(0.82 0.14 85)',  name: '포유류' },
    vir:  { c: 'oklch(0.70 0.02 220)', name: '바이러스 (비생물)' },
  };
})();
